version: '3.8'

x-defaults: &defaults
  env_file: .env

services:
  web:
    command: 'yarn start'
    # command: 'yarn start:client'
    build:
      context: .
    env_file: .env
    ports:
    - "3000:3000"
    - "3001:3001"
  postgres:
    image: postgres:13
    env_file: .env
    ports:
    - "5432:5432"
